### ISSUE TITLE
add a button on octopi page to light on/off the led

### ISSUE THREAD

**Issue by blandiant** [google/OctoPrint-LEDStripControl#20]
hi,
it would be cool if we could light on/off the led (rgb or not) with a button on octopi, like that,
 we turn on the led when we look the print with the camera and we can turn off the led after,
to consume less  electricity.
thank you

**Comment by precision** [comment]
You can already do this via the OctoPrint Configuration file ~/.octoprint/config.yaml  They show up on the Controls tab.  Just add something like this to that file.

```
controls:
- children:
  - command: M150 R
    name: Red
    type: command
  - command: M150 U
    name: Green
    type: command
  - command: M150 B
    name: Blue
    type: command
  - command: M150 W
    name: White
    type: command
  - command: M150 RUBW
    name: Bright
    type: command
  - command: M150 W64
    name: Dim
    type: command
  - command: M150
    name: Turn Off
    type: command
  layout: horizontal
  name: LEDs
```
