### ISSUE TITLE
Feature Request: UI button to run M150 command

### ISSUE THREAD

**Issue by xstrex** [google/OctoPrint-LEDStripControl#5]
So far the plugin is working great, now that I've got it figured out!

Would it be possible to add a button or two to the main UI, perhaps in the nav-bar, to run a M150 command, and turn the lights on, or off? This assumes the plugin is working, as designed. Ideally you could configure what the button did; like button A = "M150 R U B" & B = "M150 R255", etc.

**Comment by xstrex** [comment]
Currently, in order to manually turn the lights on, off, or some color, you'd have to open the UI, goto console, type "M150 R U B" or whatever. A button would streamline this process. 

Also would be nice if the LEDs could be controlled via the API, and thus by other devices on the network!

**Comment by precision** [comment]
You should be able to add buttons to the control screen for what you via the standard [Octoprint config.yaml.](http://docs.octoprint.org/en/master/configuration/config_yaml.html#controls)  The below works for me.

```
controls:
  - name: LEDs
    layout: horizontal
    children:
      - name: Red
        command: M150 R
        type: command
      - name: Green
        command: M150 U
        type: command
      - name: Blue
        command: M150 B
        type: command
      - name: White
        command: M150 RUB
        type: command
      - name: Turn Off
        command: M150
        type: command
```

As for the API, I'll add it as a possible future feature request.
